spring:
  application:
    name: productClient
  datasource:
    url: jdbc:postgresql://localhost:5432/java
    jdbcUrl: jdbc:postgresql://localhost:5432/java
    username: postgres
    password: postgres
    type: com.zaxxer.hikari.HikariDataSource
    hikari:
      driver-class-name: org.postgresql.Driver
      jdbc-url: jdbc:postgresql://localhost:5432/java
      username: postgres
      password: postgres
    driver-class-name: org.postgresql.Driver

server:
  port:
    8081




