spring:
  application:
    name: paymentCore
  datasource:
    url: jdbc:postgresql://localhost:5432/java
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: none

server:
  port:
    8080




